# .github/workflows/security.yml
name: Security Audit
on: [push, pull_request]
jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Install Soteria
        run: cargo install soteria
      - name: Run Security Analysis
        run: soteria -analyzeAll .
      - name: Run Tests
        run: anchor test
      - name: Check for Vulnerabilities
        run: cargo audit
